apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: platform
spec:
  project: platform
  source:
    repoURL: https://github.com/dmitri166/EKS_platform
    targetRevision: main
    path: platform-gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


