name: Kubernetes Lint

on:
  pull_request:
    paths:
      - 'argocd/**'
      - 'apps/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: argocd/
          directory: apps/
